In [1]:
import pandas as pd
import numpy as np
# Load the dataset
file_path = 'daily_data.csv'
data = pd.read_csv(file_path)

# Print the column names and first few rows to inspect the data
# print(data.columns)
print(data.head())

    day_id   city_id  temperature_celsius            condition_text  wind_kph  \
0  D0001    C001                     27.0                                 6.1
1  D0002    C001                     22.0                                 6.1
2  D0003    C001                     20.0  Light Rain with Thunder        3.6
3  D0004    C001                     17.0  Clear and Sunny                6.1
4  D0005    C001                     18.0                                 3.6

   wind_degree  pressure_mb  precip_mm  humidity  cloud  feels_like_celsius  \
0          210         1006        0.0        54     75                28.0
1          170         1006        0.0        73     75                24.5
2           10         1011        4.5       100     75                20.0
3          150         1018        0.0        88      0                17.0
4           92         1019        0.0        94      0                18.0

   visibility_km  uv_index  gust_kph  air_quality_us-epa-index  sunrise  \
0           10.0         6      11.9                         2  6:04 AM
1           10.0         1      23.4                         1  6:05 AM
2           10.0         1      12.6                         1  6:05 AM
3           10.0         1      11.2                         1  6:06 AM
4           10.0         1       9.0                         1  6:07 AM

    sunset
0  7:19 PM
1  7:18 PM
2  7:18 PM
3  7:16 PM
4  7:15 PM

In [2]:
data['city_id'] = data['city_id'].str.replace('C', '').astype(int)

In [3]:
# Fill missing values with column means for numeric data
modified_columns = ['city_id','temperature_celsius','condition_text', 'wind_kph', 'wind_degree', 'pressure_mb',
    'precip_mm', 'humidity', 'cloud', 'feels_like_celsius',
    'visibility_km', 'uv_index', 'gust_kph', 'air_quality_us-epa-index'
]
# Display the first few rows to verify the changes
numerical_data = data[modified_columns]
numerical_data.isnull().sum()

city_id                     0
temperature_celsius         0
condition_text              0
wind_kph                    0
wind_degree                 0
pressure_mb                 0
precip_mm                   0
humidity                    0
cloud                       0
feels_like_celsius          0
visibility_km               0
uv_index                    0
gust_kph                    0
air_quality_us-epa-index    0
dtype: int64

In [4]:
numerical_data.loc[numerical_data['condition_text'] == '', 'condition_text'] = 'null'

In [5]:
numerical_data['condition_text'] = numerical_data['condition_text'].replace(r'^\s*$', np.nan, regex=True)
numerical_data

C:\Users\himan\AppData\Local\Temp\ipykernel_17836\2556659068.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  numerical_data['condition_text'] = numerical_data['condition_text'].replace(r'^\s*$', np.nan, regex=True)

,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index
0,1,27.0,NaN,6.1,210,1006,0.0,54,75,28.0,10.0,6,11.9,2
1,1,22.0,NaN,6.1,170,1006,0.0,73,75,24.5,10.0,1,23.4,1
2,1,20.0,Light Rain with Thunder,3.6,10,1011,4.5,100,75,20.0,10.0,1,12.6,1
3,1,17.0,Clear and Sunny,6.1,150,1018,0.0,88,0,17.0,10.0,1,11.2,1
4,1,18.0,NaN,3.6,92,1019,0.0,94,0,18.0,10.0,1,9.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,112,17.1,Clear and Sunny,13.3,61,1017,0.0,57,3,17.1,10.0,1,22.2,1
2889,112,17.4,NaN,13.0,51,1017,0.0,49,0,17.4,10.0,1,22.2,1
2890,112,19.2,NaN,11.5,46,1016,0.0,34,0,19.2,10.0,1,21.3,2
2891,112,19.2,NaN,14.4,76,1017,0.0,45,2,19.2,10.0,1,24.9,2
2892,112,18.6,NaN,17.3,61,1016,0.0,34,0,18.6,10.0,1,30.2,2

In [6]:
# Convert 'sunrise' and 'sunset' to datetime format
data['sunrise'] = pd.to_datetime(data['sunrise'], format='%I:%M %p').dt.time
data['sunset'] = pd.to_datetime(data['sunset'], format='%I:%M %p').dt.time

# Calculate daylight duration in minutes
data['sunrise'] = pd.to_datetime(data['sunrise'].astype(str))
data['sunset'] = pd.to_datetime(data['sunset'].astype(str))
numerical_data['daylight_duration'] = (data['sunset'] - data['sunrise']).dt.seconds / 60

C:\Users\himan\AppData\Local\Temp\ipykernel_17836\1292378679.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['sunrise'] = pd.to_datetime(data['sunrise'].astype(str))
C:\Users\himan\AppData\Local\Temp\ipykernel_17836\1292378679.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['sunset'] = pd.to_datetime(data['sunset'].astype(str))
C:\Users\himan\AppData\Local\Temp\ipykernel_17836\1292378679.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  numerical_data['daylight_duration'] = (data['sunset'] - data['sunrise']).dt.seconds / 60

In [7]:
numerical_data

,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,daylight_duration
0,1,27.0,NaN,6.1,210,1006,0.0,54,75,28.0,10.0,6,11.9,2,795.0
1,1,22.0,NaN,6.1,170,1006,0.0,73,75,24.5,10.0,1,23.4,1,793.0
2,1,20.0,Light Rain with Thunder,3.6,10,1011,4.5,100,75,20.0,10.0,1,12.6,1,793.0
3,1,17.0,Clear and Sunny,6.1,150,1018,0.0,88,0,17.0,10.0,1,11.2,1,790.0
4,1,18.0,NaN,3.6,92,1019,0.0,94,0,18.0,10.0,1,9.0,1,788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,112,17.1,Clear and Sunny,13.3,61,1017,0.0,57,3,17.1,10.0,1,22.2,1,722.0
2889,112,17.4,NaN,13.0,51,1017,0.0,49,0,17.4,10.0,1,22.2,1,723.0
2890,112,19.2,NaN,11.5,46,1016,0.0,34,0,19.2,10.0,1,21.3,2,724.0
2891,112,19.2,NaN,14.4,76,1017,0.0,45,2,19.2,10.0,1,24.9,2,725.0
2892,112,18.6,NaN,17.3,61,1016,0.0,34,0,18.6,10.0,1,30.2,2,726.0

In [8]:
weather_mapping = {
    'Clear and Sunny': 1,
    'Partly Cloudy': 2,
    'Light Precipitation': 3,
    'Cloudy and Overcast': 4,
    'Mist or Fog': 5,
    'Rain Showers': 6,
    'Light Rain with Thunder': 7,
    'Thunderstorms': 8,
    'Moderate to Heavy Rain': 9
}

# Strip leading and trailing spaces from 'condition_text' column


# Display the updated DataFrame

In [9]:
numerical_data['condition_text'] = numerical_data['condition_text'].str.strip()
numerical_data

C:\Users\himan\AppData\Local\Temp\ipykernel_17836\894658105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  numerical_data['condition_text'] = numerical_data['condition_text'].str.strip()

,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,daylight_duration
0,1,27.0,NaN,6.1,210,1006,0.0,54,75,28.0,10.0,6,11.9,2,795.0
1,1,22.0,NaN,6.1,170,1006,0.0,73,75,24.5,10.0,1,23.4,1,793.0
2,1,20.0,Light Rain with Thunder,3.6,10,1011,4.5,100,75,20.0,10.0,1,12.6,1,793.0
3,1,17.0,Clear and Sunny,6.1,150,1018,0.0,88,0,17.0,10.0,1,11.2,1,790.0
4,1,18.0,NaN,3.6,92,1019,0.0,94,0,18.0,10.0,1,9.0,1,788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,112,17.1,Clear and Sunny,13.3,61,1017,0.0,57,3,17.1,10.0,1,22.2,1,722.0
2889,112,17.4,NaN,13.0,51,1017,0.0,49,0,17.4,10.0,1,22.2,1,723.0
2890,112,19.2,NaN,11.5,46,1016,0.0,34,0,19.2,10.0,1,21.3,2,724.0
2891,112,19.2,NaN,14.4,76,1017,0.0,45,2,19.2,10.0,1,24.9,2,725.0
2892,112,18.6,NaN,17.3,61,1016,0.0,34,0,18.6,10.0,1,30.2,2,726.0

In [10]:
# Replace categories with numerical values in 'condition_text' column
numerical_data['condition_text'] = numerical_data['condition_text'].replace(weather_mapping)
numerical_data

C:\Users\himan\AppData\Local\Temp\ipykernel_17836\1429676004.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  numerical_data['condition_text'] = numerical_data['condition_text'].replace(weather_mapping)

,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,daylight_duration
0,1,27.0,NaN,6.1,210,1006,0.0,54,75,28.0,10.0,6,11.9,2,795.0
1,1,22.0,NaN,6.1,170,1006,0.0,73,75,24.5,10.0,1,23.4,1,793.0
2,1,20.0,7.0,3.6,10,1011,4.5,100,75,20.0,10.0,1,12.6,1,793.0
3,1,17.0,1.0,6.1,150,1018,0.0,88,0,17.0,10.0,1,11.2,1,790.0
4,1,18.0,NaN,3.6,92,1019,0.0,94,0,18.0,10.0,1,9.0,1,788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,112,17.1,1.0,13.3,61,1017,0.0,57,3,17.1,10.0,1,22.2,1,722.0
2889,112,17.4,NaN,13.0,51,1017,0.0,49,0,17.4,10.0,1,22.2,1,723.0
2890,112,19.2,NaN,11.5,46,1016,0.0,34,0,19.2,10.0,1,21.3,2,724.0
2891,112,19.2,NaN,14.4,76,1017,0.0,45,2,19.2,10.0,1,24.9,2,725.0
2892,112,18.6,NaN,17.3,61,1016,0.0,34,0,18.6,10.0,1,30.2,2,726.0

In [11]:
numerical_data.head(10)

,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,daylight_duration
0,1,27.0,NaN,6.1,210,1006,0.0,54,75,28.0,10.0,6,11.9,2,795.0
1,1,22.0,NaN,6.1,170,1006,0.0,73,75,24.5,10.0,1,23.4,1,793.0
2,1,20.0,7.0,3.6,10,1011,4.5,100,75,20.0,10.0,1,12.6,1,793.0
3,1,17.0,1.0,6.1,150,1018,0.0,88,0,17.0,10.0,1,11.2,1,790.0
4,1,18.0,NaN,3.6,92,1019,0.0,94,0,18.0,10.0,1,9.0,1,788.0
5,1,20.0,NaN,3.6,96,1019,0.0,88,0,20.0,10.0,1,11.2,1,786.0
6,1,21.0,2.0,4.0,310,1015,0.0,100,50,21.0,10.0,1,15.1,2,783.0
7,1,21.0,NaN,20.2,330,1011,0.0,53,75,21.0,10.0,1,17.3,1,781.0
8,1,23.0,NaN,3.6,63,1013,0.0,47,75,24.8,10.0,1,20.5,1,778.0
9,1,24.0,NaN,15.1,330,1014,0.0,54,75,25.3,10.0,1,9.7,1,775.0

In [19]:
from sklearn.impute import KNNImputer

df = pd.DataFrame(numerical_data)
# Predictive Imputation using KNN
imputer = KNNImputer(n_neighbors=3)
df_filled =  imputer.fit_transform(numerical_data)

In [20]:
# x =df_filled['condition_text']

df_filled

array([[  1.        ,  27.        ,   2.33333333, ...,  11.9       ,
          2.        , 795.        ],
       [  1.        ,  22.        ,   3.66666667, ...,  23.4       ,
          1.        , 793.        ],
       [  1.        ,  20.        ,   7.        , ...,  12.6       ,
          1.        , 793.        ],
       ...,
       [112.        ,  19.2       ,   1.        , ...,  21.3       ,
          2.        , 724.        ],
       [112.        ,  19.2       ,   1.        , ...,  24.9       ,
          2.        , 725.        ],
       [112.        ,  18.6       ,   1.        , ...,  30.2       ,
          2.        , 726.        ]])

In [21]:
col_names = ['city_id','temperature_celsius','condition_text', 'wind_kph', 'wind_degree', 'pressure_mb',
    'precip_mm', 'humidity', 'cloud', 'feels_like_celsius', 'visibility_km', 'uv_index', 'gust_kph', 'air_quality_us-epa-index','daylight_duration']
df_filled = pd.DataFrame(df_filled, columns=col_names)
df_filled

,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,daylight_duration
0,1.0,27.0,2.333333,6.1,210.0,1006.0,0.0,54.0,75.0,28.0,10.0,6.0,11.9,2.0,795.0
1,1.0,22.0,3.666667,6.1,170.0,1006.0,0.0,73.0,75.0,24.5,10.0,1.0,23.4,1.0,793.0
2,1.0,20.0,7.000000,3.6,10.0,1011.0,4.5,100.0,75.0,20.0,10.0,1.0,12.6,1.0,793.0
3,1.0,17.0,1.000000,6.1,150.0,1018.0,0.0,88.0,0.0,17.0,10.0,1.0,11.2,1.0,790.0
4,1.0,18.0,4.000000,3.6,92.0,1019.0,0.0,94.0,0.0,18.0,10.0,1.0,9.0,1.0,788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,112.0,17.1,1.000000,13.3,61.0,1017.0,0.0,57.0,3.0,17.1,10.0,1.0,22.2,1.0,722.0
2889,112.0,17.4,1.000000,13.0,51.0,1017.0,0.0,49.0,0.0,17.4,10.0,1.0,22.2,1.0,723.0
2890,112.0,19.2,1.000000,11.5,46.0,1016.0,0.0,34.0,0.0,19.2,10.0,1.0,21.3,2.0,724.0
2891,112.0,19.2,1.000000,14.4,76.0,1017.0,0.0,45.0,2.0,19.2,10.0,1.0,24.9,2.0,725.0
2892,112.0,18.6,1.000000,17.3,61.0,1016.0,0.0,34.0,0.0,18.6,10.0,1.0,30.2,2.0,726.0

In [22]:
df_filled['condition_text'] = df_filled['condition_text'].round(0)
df_filled

,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,daylight_duration
0,1.0,27.0,2.0,6.1,210.0,1006.0,0.0,54.0,75.0,28.0,10.0,6.0,11.9,2.0,795.0
1,1.0,22.0,4.0,6.1,170.0,1006.0,0.0,73.0,75.0,24.5,10.0,1.0,23.4,1.0,793.0
2,1.0,20.0,7.0,3.6,10.0,1011.0,4.5,100.0,75.0,20.0,10.0,1.0,12.6,1.0,793.0
3,1.0,17.0,1.0,6.1,150.0,1018.0,0.0,88.0,0.0,17.0,10.0,1.0,11.2,1.0,790.0
4,1.0,18.0,4.0,3.6,92.0,1019.0,0.0,94.0,0.0,18.0,10.0,1.0,9.0,1.0,788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2888,112.0,17.1,1.0,13.3,61.0,1017.0,0.0,57.0,3.0,17.1,10.0,1.0,22.2,1.0,722.0
2889,112.0,17.4,1.0,13.0,51.0,1017.0,0.0,49.0,0.0,17.4,10.0,1.0,22.2,1.0,723.0
2890,112.0,19.2,1.0,11.5,46.0,1016.0,0.0,34.0,0.0,19.2,10.0,1.0,21.3,2.0,724.0
2891,112.0,19.2,1.0,14.4,76.0,1017.0,0.0,45.0,2.0,19.2,10.0,1.0,24.9,2.0,725.0
2892,112.0,18.6,1.0,17.3,61.0,1016.0,0.0,34.0,0.0,18.6,10.0,1.0,30.2,2.0,726.0

In [23]:
# Choose randomly for training and testing
from sklearn.model_selection import train_test_split
X = df_filled.drop('condition_text', axis=1)
y = df_filled['condition_text']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
# Train a Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [25]:
# Predict the labels for the test set
y_pred = rf.predict(X_test)

In [26]:
# Evaluate the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.55